### PR TITLE
CHG: Add armadillo typedef fixed support

### PR DESCRIPTION
**Pull request by mlouielu**
armadillo have define some fixed size typedef for Mat/Col/Row,
e.g. arma::vec3, arma::mat33, which benifit the performance
needed case.

This commit add them into `utils.h` so they can be supported in
auto type casting from pybind11.

The list is scan and generate from:
`./third_party/armadillo-code/include/armadillo_bits/typedef_mat_fixed.hpp`,
and skip some duplicate define including:

* arma::d*        (e.g. arma::dvec)
* arma::*_d*      (e.g. arma::cx_drowvec)
* arma::*colvec*  (e.g. arma::colvec)

### CODE REVIEW

**Comment by RUrlus** [comment]
Hi Louie, thanks for the PR. Sorry I haven't been able to respond earlier.
Could you add a test to make sure that it works and keeps working if we change something in the future?

If not, I will do so but I can't give a clear timeline on when.

**Comment by mlouielu** [comment]
Do we need to add all of the types (e.g. from vec2 to vec9) in the test, or just a portion of them?

**Comment by RUrlus** [comment]
No, it would be great if we have one for each of the fixed types (Mat, Row, Col, Cube).
The tests are failing for the debug builds, Armadillo does some checking for those, and this triggers the error on passing a (4, 4) matrix

The tests can be very simple, I just want to make sure the templates work for the fixed size types. All the proper checks can be handled by the other tests

**Comment by mlouielu** [comment]
> No, it would be great if we have one for each of the fixed types (Mat, Row, Col, Cube).

Got it!

> The tests are failing for the debug builds, Armadillo does some checking for those, and this triggers the error on passing a (4, 4) matrix
> 

That should be correct, but I don't know why it won't raised RuntimeError when using release build.

Since fixed type will allocated exact memory size, an in type of `mat33` should only accept mat with size (3,3)

```c++
#include <iostream>

#include <armadillo>

double a(const arma::mat33 &m) { return arma::accu(m); }

int main() {
  arma::mat33 m(arma::fill::randu);
  arma::mat mm(3, 3, arma::fill::randu);
  arma::mat mmm(2, 2, arma::fill::randu);
  std::cout << a(m) << std::endl;
  std::cout << a(mm) << std::endl;
  std::cout << a(mmm) << std::endl;
}
```

Running with:

```
➜  /tmp g++ -larmadillo foo.cpp
➜  /tmp ./a.out
3.91349
4.16193

error: Mat::init(): size is fixed and hence cannot be changed
terminate called after throwing an instance of 'std::logic_error'
  what():  Mat::init(): size is fixed and hence cannot be changed
[2]    57340 abort (core dumped)  ./a.out
```

Last with `a(mat22)` should raise runtime error

**Comment by mlouielu** [comment]
This is cause by `armadillo_bits/debug.hpp`, I believe when using `Release` build, it will then set

* ARMA_NO_DEBUG=True

Then will remove `arma_debug_set_error` to be used.

**Comment by RUrlus** [comment]
Yes, we set no_debug for releases, which is a debatable choice. You could create a test that only should trigger on Debug builds.

**Comment by RUrlus** [comment]
I'll merge the branche into unstable after completing the last changes there

**Pull request closed without merging**
