### PR TITLE
Move armadillo and pybind11 as third_party submodules and use generated modules from build directory

### PR DESCRIPTION
**Pull request by hpwxf**
As proposed in #24, this PR remove Pybind11 and Armadillo from the source tree and use them as submodules (linked to armadillo-9.800.x and pybind11-2.4 as described in README.md).

Except for commit c998cfa, which is a fix of misspellings (`RELEASEE` fixed as `RELEASE`), the 3 commits are one dev but split to be more readable.

`make install` installs tests, examples, and headers in `CMAKE_INSTALL_PREFIX` directory. 

Tests are run using generated modules from *build* directory (not copied inside `tests` or `examples` directories to prevent to overwrite module generated by another build configuration).

NB: `tests` and `examples` directories are now managed using `add_subdirectory` (to have a scope for each subdir).

### CODE REVIEW

**Comment by hpwxf** [comment]
NB: `carma_examples` has been renamed as `example_carma` so that it does not conflict with py file when it is not in the same directory.

**Comment by RUrlus** [comment]
Nice, a lot cleaner than what I had.

What do you think about copying the tests and examples to its respective directory when the respective flag is on?
With the current approach you need to change the python path for the tests to run.

**Comment by hpwxf** [comment]
In next commit (ready to PR), I have plugged ctest, so that, you just have to type ’ctest’ after ‘make’.

After ‘make install’ tests and examples are copied in installation directory next to python module. 
In that case, one can run them without any environment variable.

**Comment by hpwxf** [comment]
If you prefer, I can add my ‘ctest’ integration in this PR.

**Comment by RUrlus** [comment]
No strong preference, happy to merge this

**Pull request merged**
